name: Send Email

on:
  # Allows triggering the workflow manually from the Actions tab with a custom subject and body
  workflow_dispatch:
    inputs:
      subject:
        description: 'Email subject'
        required: true
        default: '🏈 Fantasy Football Tuesday Waiver & News Briefing'
      body:
        description: 'Email body'
        required: true
        default: 'Test'

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
            # SMTP Server Configuration
            server_address: smtp.gmail.com
            server_port: 465
            secure: true

            # Authentication Secrets
            username: ${{ secrets.MAIL_USERNAME }}
            password: ${{ secrets.MAIL_PASSWORD }}

            # Email Details
            subject: ${{ github.event.inputs.subject }}
            to: ${{ vars.EMAIL }}
            from: "Football God <${{ secrets.MAIL_USERNAME }}>"

            # Reads the generated content directly from file
            body: ${{ github.event.inputs.body }}